language: objective-c
osx_image: xcode7.1
branches:
  only:
    - master
env:
  matrix:
    - DESTINATION="OS=9.1,name=iPad 2"
before_install:
  - gem install xcpretty
script:
  - xcodebuild -version
  - xcodebuild -project Example/SplitflapExample.xcodeproj -scheme SplitflapTests -sdk iphonesimulator -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
